import React from "react";
import { FaReact, FaNode, FaBootstrap, FaAws, FaCss3, FaHtml5 } from "react-icons/fa";
import { DiRuby } from "react-icons/di";
import { SiHeroku, SiReactrouter, SiPostgresql, SiJavascript, SiRedux, SiFirebase, SiRails, SiStyledComponents} from "react-icons/si"

export const mainProjects = [
  { 
    id: "facebook-clone",
    name: "Facebook Clone",
    bgColor: "white",
    textColor: "#101522",
    images: [
      { src: require("../../images/facebook6.png"), idx: 0 },
      { src: require("../../images/facebook2.png"), idx: 1 },
      { src: require("../../images/facebook3.png"), idx: 2 },
      { src: require("../../images/facebook4.png"), idx: 3 },
      { src: require("../../images/facebook5.png"), idx: 4 },
    ],
    techIcons: [
      <SiRails color="red"/>,
      <DiRuby color="red" />,
      <FaBootstrap color="purple"/>,
      <FaHtml5 color="orange"/>,
      <FaCss3 color="blue"/>,
      <SiPostgresql color="green"/>,
      <FaAws color="orange"/>,
      <SiHeroku color="violet"/>,
    ],
    desc: "A facebook clone built with ruby on rails. This was a great challenge for me, I learned a lot of about Rails' Model-View-Controller arhitecture, Forms, HTTP requests, Relational Databases and so much more.",
    features:
      "Responsive Design, Facebook oAuth, Email Confirmation, Posts, Comments, Replies, Post/Comment Likes, Friend Requests and more. Try it out right now.",
    liveURL: "https://whispering-bayou-85275.herokuapp.com/",
    codeURL: "https://github.com/irlgabriel/facebook-odin",
    projectIcon: <DiRuby fontSize="2.5rem" color="red"/>,
    key: "1",
  },
  {
    name: "Weather App",
    id: "weather-app",
    bgColor: "#101522",
    textColor: "white",
    images: [
      { src: require("../../images/weather2.png"), idx: 0 },
      { src: require("../../images/weather3.png"), idx: 1 },
      { src: require("../../images/weather4.png"), idx: 2 },
    ],
    techIcons: [
      <FaReact color="lightblue"/>,
      <SiStyledComponents color="gray"/>,
      <SiJavascript color="yellow"/>,
      <FaHtml5 color="orange"/>,
      <FaCss3 color="blue"/>,
    ],
    desc: "An ugly weather app that takes data from OpenWeatherMap API and display weather forecast based on your location or the city that you input. This application learned me to be a lot more thoughtful about how to handle state updates.",
    features: "See the weather forecast for your city this coming week!",
    liveURL: "https://irlgabriel.github.io/weather-app/",
    codeURL: "https://github.com/irlgabriel/weather-app/",
    projectIcon: <FaReact fontSize="2.5rem" color="lightblue"/>,
    key: "2",
  },
  {
    name: "MERN Shopping List",
    id: "mern-app",
    bgColor: "white",
    textColor: "#101522",
    images: [
      { src: require("../../images/mern1.png"), idx: 0 },
      { src: require("../../images/mern2.png"), idx: 1 },
    ],
    techIcons: [
      <FaNode color="green"/>,
      //"Express.js",
      //"JWT Auth",
      <FaReact color="lightblue"/>,
      <SiRedux color="purple"/>,
      <SiHeroku color="pink"/>,
      <SiJavascript color="yellow"/>,
      <FaBootstrap color="purple"/>,
      <FaHtml5 color="orange"/>,
      <FaCss3 color="blue"/>,
    ],
    desc: "A simple shopping list built with the MERN stack. I know it is pointless and overkill to have a custom back-end for such an app while I could have used firebase or other BaaS but I created this one to get familiar with node, Express and mongoDB. I plan to turn it into a e-commerce style website with items and a shopping cart in the future",
    features:
      "Just a shopping list that you can add and remove items(once you log in). I know it is overkill to have a full stack app for this purpose, but I only built it to get familiar with node, express and redux. I will expand on this app's functionality very soon.",
    liveURL: "https://tranquil-anchorage-36599.herokuapp.com",
    codeURL: "https://github.com/irlgabriel/mern-shopping-list",
    projectIcon: <FaNode fontSize="2.5rem" color="lightgreen"/>,
    key: "3",
  },
  {
    name: "CV Generator",
    id: "cv-generator",
    images: [
      { src: require("../../images/project3.png"), idx: 0 },
      { src: require("../../images/cv2.png")}
  ],
    techIcons: [
      <FaReact color="lightblue"/>,
      <SiJavascript color="yellow"/>,
      <SiStyledComponents color="gray"/>,
      <FaHtml5 color="orange"/>,
      <FaCss3 color="blue"/>,
    ],
    smallDesc: "A simple app that helps you generate a CV!",
    features: "Responsive Design, Create/Edit individual parts of your CV!",
    liveURL: "https://irlgabriel.github.io/Cv-project",
    codeURL: "https://github.com/irlgabriel/Cv-project",
    projectIcon: <FaReact />,
    key: "3",
  },
  {
    name: "Book Library",
    images: [
      { src: require("../../images/library3.png"), idx: 0 },
      { src: require("../../images/library4.png"), idx: 1 },
      { src: require("../../images/library5.png"), idx: 2 },
    ],
    alt: "Photo of library project",
    projectTitle: "Library",
    techIcons: [
      <FaReact color="lightblue"/>,
      <SiReactrouter />,
      <SiJavascript color="yellow"/>,
      <SiFirebase color="orange"/>,
      <SiStyledComponents color="gray"/>,
      <FaHtml5 color="orange"/>,
      <FaCss3 color="blue"/>,
    ],
    smallDesc: "A small app for book lovers!",
    features:
      "Store your favorite books in an aesthetically pleasing way with this small app powered by the latest technologies!",
    liveURL: "https://irlgabriel.github.io/library-project-redo/#/",
    codeURL: "https://github.com/irlgabriel/library-project-redo/",
    projectIcon: <FaReact />,
    key: "4",
  },
  {
    name: "Netflix Memory Game",
    id: "netflix-memory-game",
    images: [
      { src: require("../../images/memory-game.png"), idx: 0 },
      { src: require("../../images/memory-game-2.png"), idx: 1 },
      { src: require("../../images/memory-game-3.png"), idx: 2 },
    ],
    techIcons: [
      <FaReact color="lightblue"/>,
      <SiJavascript color="yellow"/>,
      <SiStyledComponents color="gray"/>,
      <FaHtml5 color="orange"/>,
      <FaCss3 color="blue"/>,
    ],
    smallDesc:
      "Small app to practice your memory (and my ReactJS effect and state hooks)",
    features: "Test you memory with this netflix-themed memory game.",
    liveURL: "https://irlgabriel.github.io/memory-card-game/#/",
    codeURL: "https://github.com/irlgabriel/memory-card-game",
    projectIcon: <FaReact />,
    key: "5",
  },
  
];
