export { default as Header } from './Header';
export { default as Intro } from './Intro';
export { default as Projects } from './Projects';
export { default as Project } from './Project';
export { default as Skills } from './Skills';
export { default as Contact } from './Contact';
export { default as About } from './About';
export { default as SkillSection } from './SkillSection';
export { default as TimeTable } from './TimeTable';